import 'package:flutter_test/flutter_test.dart';
import 'package:themealdb/features/domain/entites/details_meal.dart';

class DetailsMealTest extends DetailsMeal {
  DetailsMealTest(
      {required super.strMeal,
      required super.strMealThumb,
      required super.idMeal,
      required super.strCategory,
      required super.strArea,
      required super.strInstructions,
      required super.strYoutube,
      required super.strIngredient1,
      required super.strIngredient2,
      required super.strIngredient3,
      required super.strIngredient4,
      required super.strIngredient5,
      required super.strIngredient6,
      required super.strIngredient7,
      required super.strIngredient8,
      required super.strIngredient9,
      required super.strIngredient10,
      required super.strIngredient11,
      required super.strIngredient12,
      required super.strIngredient13,
      required super.strIngredient14,
      required super.strIngredient15,
      required super.strMeasure1,
      required super.strMeasure2,
      required super.strMeasure3,
      required super.strMeasure4,
      required super.strMeasure5,
      required super.strMeasure6,
      required super.strMeasure7,
      required super.strMeasure8,
      required super.strMeasure9,
      required super.strMeasure10,
      required super.strMeasure11,
      required super.strMeasure12,
      required super.strMeasure13,
      required super.strMeasure14,
      required super.strMeasure15});
}

void main() {
  test('Testing DetailsMeal  class en equality', () {
  DetailsMealTest s1 = DetailsMealTest(
      strMeal: 'kk',
      strMealThumb: 'dgs',
      idMeal: '5412',
      strCategory: 'gf',
      strArea: 'lkgd',
      strIngredient1: '',
      strIngredient2: '',
      strIngredient3: '',
      strIngredient4: '',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strInstructions: '',
      strMeasure1: '',
      strMeasure2: '',
      strMeasure3: '',
      strMeasure4: '',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strYoutube: '');
  DetailsMealTest s2 = DetailsMealTest(
      strMeal: 'kk',
      strMealThumb: 'dgs',
      idMeal: '5412',
      strCategory: 'gf',
      strArea: 'lkgd',
      strIngredient1: '',
      strIngredient2: '',
      strIngredient3: '',
      strIngredient4: '',
      strIngredient5: '',
      strIngredient6: '',
      strIngredient7: '',
      strIngredient8: '',
      strIngredient9: '',
      strIngredient10: '',
      strIngredient11: '',
      strIngredient12: '',
      strIngredient13: '',
      strIngredient14: '',
      strIngredient15: '',
      strInstructions: '',
      strMeasure1: '',
      strMeasure2: '',
      strMeasure3: '',
      strMeasure4: '',
      strMeasure5: '',
      strMeasure6: '',
      strMeasure7: '',
      strMeasure8: '',
      strMeasure9: '',
      strMeasure10: '',
      strMeasure11: '',
      strMeasure12: '',
      strMeasure13: '',
      strMeasure14: '',
      strMeasure15: '',
      strYoutube: '');

  expect(s1 == s2, true);
});
}